apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: &app notification
spec:
  type: ClusterIP

  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: *app